Feature/guild dashboard
RainbowDashLabs/reputation-bot pull request #112
Opened 2021-07-09 14:45 UTC by RainbowDashLabs

Introduces a guild dashboard which provides basic insight into guild statistics.

Closes #110

2021-07-09 16:09 UTC, Taucher2003 requested changes

2021-07-09 16:09 UTC, Taucher2003 commented on src/main/resources/locale_fr_FR.properties
> +command.dashboard.title=Informations sur le %GUILD
```suggestion
command.dashboard.title=Informations sur le %GUILD%
```

2021-07-09 18:20 UTC, Taucher2003 approved these changes

2021-07-10 11:18 UTC, dlsf requested changes

2021-07-10 11:18 UTC, dlsf commented on src/main/resources/locale.properties
> +command.dashboard.todayReputation=Today Reputation
```suggestion
command.dashboard.todayReputation=Reputation today
```

2021-07-10 11:18 UTC, dlsf commented on src/main/resources/locale.properties
> +command.dashboard.todayReputation=Today Reputation
```suggestion
command.dashboard.todayReputation=Todays Reputation
```

2021-07-10 11:18 UTC, dlsf commented on src/main/resources/locale.properties
> +command.dashboard.todayReputation=Today Reputation
Choose your fighter

2021-07-10 11:18 UTC, dlsf commented on src/main/resources/locale_de_DE.properties
> +command.dashboard.description=Erhalten Informationen über diesen Server.
Other command descriptions don't directly address the reader. Additionally, this is grammatically wrong.
```suggestion
command.dashboard.description=Zeigt Informationen über diesen Server an.
```

2021-07-10 11:18 UTC, dlsf commented on src/main/resources/locale_en_US.properties
> +command.dashboard.todayReputation=Today Reputation
```suggestion
command.dashboard.todayReputation=Todays Reputation
```

2021-07-10 11:18 UTC, dlsf commented on src/main/resources/locale_en_US.properties
> +command.dashboard.todayReputation=Today Reputation
```suggestion
command.dashboard.todayReputation=Reputation today
```

2021-07-10 17:22 UTC, dlsf approved these changes

2021-07-10 17:43 UTC, merged