Feature: Send fancy image sometimes
RainbowDashLabs/reputation-bot pull request #20
Opened 2021-05-06 18:17 UTC by Amejonah1200

2021-05-07 22:02 UTC, yannicklamprecht requested changes

2021-05-07 22:02 UTC, yannicklamprecht commented on src/main/java/de/chojo/repbot/manager/ReputationManager.java
> +                    .queue(message1 -> message1.delete().queueAfter(1, TimeUnit.MINUTES));
Make value configurable.

2021-05-07 22:02 UTC, yannicklamprecht commented on src/main/java/de/chojo/repbot/manager/ReputationManager.java
> +            if (lastEasterEggSent.until(Instant.now(), ChronoUnit.MINUTES) > 30
Make value configureable.

2021-05-07 22:02 UTC, yannicklamprecht commented on src/main/java/de/chojo/repbot/manager/ReputationManager.java
> +                    .setImage("https://cdn.discordapp.com/attachments/466561879674847233/839921810714656818/cover1.png")
Make value configureable.
Especially when the image ever gets removed.

2021-05-19 15:41 UTC, RainbowDashLabs requested changes

2021-05-19 15:41 UTC, RainbowDashLabs commented on src/main/java/de/chojo/repbot/config/Configuration.java
> +    }
Setters are not required, since we dont want to change the values in runtime anyway.

2021-05-19 15:41 UTC, RainbowDashLabs commented on src/main/java/de/chojo/repbot/config/ConfigFile.java
> +    private int magicImageDeleteSchedule = 60;
Please wrap these values into an own class.

2021-05-19 15:56 UTC, RainbowDashLabs requested changes

2021-05-19 15:56 UTC, RainbowDashLabs commented on src/main/java/de/chojo/repbot/config/Configuration.java
> +    }
please only delegate to the getMagicImage object and unwrap the values where you need them.

2021-05-19 17:47 UTC, RainbowDashLabs approved these changes

2021-05-19 18:01 UTC, yannicklamprecht requested changes

2021-05-19 18:01 UTC, yannicklamprecht commented on src/main/java/de/chojo/repbot/manager/ReputationManager.java
> +                    .setImage(magicImage.getMagicImageLink())
What happens if the image link is non valid URL or just empty string?

2021-05-19 18:27 UTC, yannicklamprecht approved these changes

2021-05-19 18:36 UTC, merged