Fix exception in emoji usability check
RainbowDashLabs/reputation-bot pull request #265
Opened 2022-05-03 19:51 UTC by Taucher2003

It looks like there is a case where `Guild#retrieveEmoteById` returns an emote which is not usable in the context of the channel.

I don't know if we should treat it like `NOT_FOUND` or if this should be its own status in CheckResult.

[Exceptions in Log (internal)](https://canary.discord.com/channels/853250161915985958/853262532261576724/971117072291606538)

2022-05-03 20:33 UTC, yannicklamprecht approved these changes

2022-05-03 21:25 UTC, RainbowDashLabs requested changes
Maybe UNKNOWN_EMOJI would be more suitable. Or we should add a extra type for missing access to the emoji. At least not found might be actually the wrong response, since this would mean, that we didnt found any emote/emoji in the argument, which is in fact not true :thinking:

2022-05-04 17:05 UTC, Taucher2003 commented
`NOT_FOUND` produces `Could not find emote on server.` while `UNKNOWN_EMOJI` will give the more generic `No emoji or emote found.`. I think, the message of `NOT_FOUND` fits better. Maybe we need to go with an own message and result

2022-05-05 09:14 UTC, RainbowDashLabs approved these changes
In this case its fine I think.

2022-05-05 09:14 UTC, merged