Initial pass on setup command
RainbowDashLabs/reputation-bot pull request #78
Opened 2021-06-18 18:36 UTC by RainbowDashLabs

Creates a setup command which makes the setup as simple as possible.

2021-06-18 21:32 UTC, yannicklamprecht approved these changes
LGTM

2021-06-18 22:16 UTC, dlsf requested changes

2021-06-18 22:16 UTC, dlsf commented on src/main/java/de/chojo/repbot/commands/Invite.java
> +}
Missing newline

2021-06-18 22:16 UTC, dlsf commented on src/main/java/de/chojo/repbot/commands/Thankwords.java
> +}
Missing newline

2021-06-18 22:16 UTC, dlsf commented on src/main/java/de/chojo/repbot/serialization/ThankwordsContainer.java
> +    public ThankwordsContainer() {
Comment why this constructor is empty or remove it

2021-06-18 22:16 UTC, dlsf commented on src/main/resources/database/1/patch_3.sql
> +from temp_channel;
Missing newline

2021-06-18 22:16 UTC, dlsf commented on src/main/resources/locale_de_DE.properties
> +conversation.exit=beenden
This should probably be uppercase?

2021-06-18 22:42 UTC, yannicklamprecht commented on src/main/resources/locale_de_DE.properties
> +conversation.exit=beenden
```suggestion
conversation.exit=Beenden
```

2021-06-18 22:42 UTC, yannicklamprecht commented on src/main/java/de/chojo/repbot/commands/Invite.java
> +}
```suggestion
}

```

2021-06-18 22:43 UTC, yannicklamprecht commented on src/main/java/de/chojo/repbot/commands/Thankwords.java
> +}
```suggestion
}

```

2021-06-18 22:43 UTC, yannicklamprecht commented on src/main/resources/database/1/patch_3.sql
> +from temp_channel;
```suggestion
from temp_channel;

```

2021-06-19 12:33 UTC, dlsf approved these changes

2021-06-19 12:40 UTC, merged