Feature/gdpr
RainbowDashLabs/reputation-bot pull request #89
Opened 2021-06-28 21:31 UTC by RainbowDashLabs

Adds a gdpr command to the bot which allows user to request their data or its deletion.

Deletion and sending of data will be done hourly.

Close #87

2021-06-28 22:04 UTC, Taucher2003 requested changes

2021-06-28 22:04 UTC, Taucher2003 commented on src/main/resources/database/1/patch_5.sql
> +    return _result;
```suggestion
    FROM reputation,
         voice_activity
    INTO _result;
    RETURN _result;
```

2021-06-28 22:04 UTC, Taucher2003 commented on src/main/resources/database/1/patch_5.sql
> +alter table repbot_schema.cleanup_schedule alter column user_id set default 0;
```suggestion
CREATE TABLE IF NOT EXISTS repbot_schema.gdpr_log
(
    user_id  BIGINT NOT NULL,
    received TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS gdpr_log_user_id_uindex
    ON repbot_schema.gdpr_log (user_id);

ALTER TABLE repbot_schema.cleanup_schedule ALTER COLUMN guild_id SET DEFAULT 0;

ALTER TABLE repbot_schema.cleanup_schedule ALTER COLUMN user_id SET DEFAULT 0;
```

2021-06-28 22:04 UTC, Taucher2003 commented on src/main/resources/locale.properties
> +command.gdpr.sub.request.requested=Your have requested your data in the last 30 days. You can request your data only every 30 days.
```suggestion
command.gdpr.sub.request.requested=You have requested your data in the last 30 days. You can request your data only every 30 days.
```

2021-06-28 22:04 UTC, Taucher2003 commented on src/main/resources/locale_en_US.properties
> +command.gdpr.sub.request.requested=Your have requested your data in the last 30 days. You can request your data only every 30 days.
```suggestion
command.gdpr.sub.request.requested=You have requested your data in the last 30 days. You can request your data only every 30 days.
```

2021-06-28 23:10 UTC, DRSchlaubi approved these changes

2021-06-29 11:07 UTC, dlsf requested changes
There is a synonym for "beantragen" which is maybe more fitting but I forgot it

2021-06-29 11:07 UTC, dlsf commented on src/main/resources/locale_de_DE.properties
> +command.gdpr.description=Frage eine Kopie oder die Löschung deiner Daten an.
```suggestion
command.gdpr.description=Beantrage eine Kopie oder die Löschung deiner Daten.
```

2021-06-29 11:07 UTC, dlsf commented on src/main/resources/locale_de_DE.properties
> +command.gdpr.sub.delete=Frage die Löschung deiner Daten an.
```suggestion
command.gdpr.sub.delete=Beantrage die Löschung deiner Daten.
```

2021-06-29 11:07 UTC, dlsf commented on src/main/resources/locale_de_DE.properties
> +command.gdpr.sub.delete.received=Deine Daten sind zur Löschung freigegeben. Sie werden innterhalb der nächsten Stunden gelöscht.
```suggestion
command.gdpr.sub.delete.received=Deine Daten sind zur Löschung freigegeben. Sie werden innerhalb der nächsten Stunden entfernt.
```

2021-06-29 11:07 UTC, dlsf commented on src/main/resources/locale_de_DE.properties
> +command.gdpr.sub.delete.scheduled=Deine Daten sind bereits zur Löschung freigegeben. Sie werden in den nächsten Stunden gelöscht.
```suggestion
command.gdpr.sub.delete.scheduled=Deine Daten sind bereits zur Löschung freigegeben. Sie werden in den nächsten Stunden entfernt.
```

2021-06-29 11:07 UTC, dlsf commented on src/main/resources/locale_de_DE.properties
> +command.gdpr.sub.request=Frage eine Kopie deiner Daten an.
```suggestion
command.gdpr.sub.request=Beantrage eine Kopie deiner Daten.
```

2021-06-29 11:36 UTC, RainbowDashLabs commented
> There is a synonym for "beantragen" which is maybe more fitting but I forgot it

Nothing is for ever :D We can always change it in the future :D

2021-06-29 14:27 UTC, dlsf approved these changes

2021-06-29 16:47 UTC, merged