Initial implementation of prune command
RainbowDashLabs/reputation-bot pull request #93
Opened 2021-07-01 18:01 UTC by RainbowDashLabs

Add a command to remove reputation of a user.
Add a command to remove reputation of no longer present users

Close #92

2021-07-01 18:27 UTC, Taucher2003 commented on src/main/java/de/chojo/repbot/commands/Prune.java
> +                return true;
Looks like the reply is missing here

2021-07-01 18:27 UTC, Taucher2003 commented on src/main/resources/locale_de_DE.properties
> +command.prune.sub.guild.started=Beginne mit entfernen von nicht existierenden Nutzern.
```suggestion
command.prune.sub.guild.started=Beginne mit dem Entfernen von nicht existierenden Nutzern.
```

2021-07-01 18:34 UTC, RainbowDashLabs commented on src/main/java/de/chojo/repbot/commands/Prune.java
> +                return true;
Indeed

2021-07-01 18:41 UTC, Taucher2003 approved these changes
Looks good to me

2021-07-02 07:21 UTC, yannicklamprecht requested changes

2021-07-02 07:21 UTC, yannicklamprecht commented on src/main/resources/locale.properties
> +command.prune.sub.user=Remove reputation of a user from the server.
```suggestion
command.prune.sub.user=Remove reputation of an user from the server.
```

2021-07-02 07:21 UTC, yannicklamprecht commented on src/main/resources/locale_en_US.properties
> +command.prune.sub.user=Remove reputation of a user from the server.
```suggestion
command.prune.sub.user=Remove reputation of an user from the server.
```

2021-07-02 11:54 UTC, yannicklamprecht approved these changes
Lgn

2021-07-02 12:16 UTC, merged